[build]
  functions = "functions"

[[redirects]]
  from = "/product/:id"
  to = "/product/*"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''