export const vortextProducts = [
  {
    code: "BucketP100B_1000M_30D",
    name: "Free Bee 1000",
    description:
      "Enjoy 1000 minutes to call any PLDT Landline, Smart. Talk N' Text and Sun Cellular numbers, valid for 30 days.",
    category: "Eload",
    subcategory: "RTR",
    brand: "FREEBEE",
    model: "Free Bee",
    pricing: {
      unit: "USD",
      price: 10.0,
      dispensingDiscount: 4.4,
      computedAmount: 9.56,
    },
  },
  {
    code: "BucketP100B_100mins_7D",
    name: "Free Bee 100",
    description:
      "Enjoy 100 minutes to call any PLDT Landline, Smart. Talk N' Text and Sun Cellular numbers, valid for 7 days.",
    category: "Eload",
    subcategory: "RTR",
    brand: "FREEBEE",
    model: "Free Bee",
    pricing: {
      unit: "USD",
      price: 2.0,
      dispensingDiscount: 4.4,
      computedAmount: 1.912,
    },
  },
  {
    code: "BucketP100B_500M_30D",
    name: "Free Bee 500",
    description:
      "Enjoy 500 minutes to call any PLDT Landline, Smart. Talk N' Text and Sun Cellular numbers, valid for 30 days.",
    category: "Eload",
    subcategory: "RTR",
    brand: "FREEBEE",
    model: "Free Bee",
    pricing: {
      unit: "USD",
      price: 5.0,
      dispensingDiscount: 4.4,
      computedAmount: 4.78,
    },
  },
  {
    code: "BucketP5B_500M_30D",
    name: "BucketP5B_500M_30D",
    description:
      "500 IDD minutes to call Smart, Sun & PLDT numbers in the Philippines, valid for 30 days from first use.",
    category: "Eload",
    subcategory: "ELOAD",
    brand: "PLDTPH",
    model: "Topup",
    pricing: {
      unit: "USD",
      price: 3.5,
      dispensingDiscount: 4.4,
      computedAmount: 3.346,
    },
  },
  {
    code: "BucketPL5B_1000mins_30D",
    name: "BucketPL5B_1000mins_30D",
    description:
      "1000 IDD minutes to call Smart, Sun & PLDT numbers in the Philippines, valid for 30 days from first use.",
    category: "Eload",
    subcategory: "ELOAD",
    brand: "PLDTPH",
    model: "Topup",
    pricing: {
      unit: "USD",
      price: 6.5,
      dispensingDiscount: 4.4,
      computedAmount: 6.214,
    },
  },
  {
    code: "Pin Sku",
    name: "Pin Sku",
    description: "Pin Sku",
    category: "Eload",
    subcategory: "PIN",
    brand: "FREEBEE",
    model: "Topup",
    pricing: {
      unit: "USD",
      price: 2.0,
      dispensingDiscount: 4.4,
      computedAmount: 1.912,
    },
  },
  {
    code: "W100",
    name: "Smart Load 100",
    description: "P100 worth of airtime load valid for 1 year",
    category: "Eload",
    subcategory: "RTR",
    brand: "SMARTPH",
    model: "Topup",
    pricing: {
      unit: "USD",
      price: 2.0,
      dispensingDiscount: 4.4,
      computedAmount: 1.912,
    },
  },
  {
    code: "W300",
    name: "Smart Load 300",
    description: "P300 worth of airtime load valid for 1 year",
    category: "Eload",
    subcategory: "RTR",
    brand: "SMARTPH",
    model: "Smart Model",
    pricing: {
      unit: "USD",
      price: 6.0,
      dispensingDiscount: 4.4,
      computedAmount: 5.736,
    },
  },
  {
    code: "W500",
    name: "Smart Load 500",
    description: "P500 worth of airtime load valid for 1 year",
    category: "Eload",
    subcategory: "RTR",
    brand: "SMARTPH",
    model: "Smart Model",
    pricing: {
      unit: "USD",
      price: 10.0,
      dispensingDiscount: 4.4,
      computedAmount: 9.56,
    },
  },
  {
    code: "WGIGA299",
    name: "GigaSurf 299",
    description:
      "4GB + 1GB / day of Video Every Day for YouTube, iFlix, iWant TV, NBA League Pass, Cignal TV, valid for 30 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "SMARTPH",
    model: "Smart Model",
    pricing: {
      unit: "USD",
      price: 6.0,
      dispensingDiscount: 4.4,
      computedAmount: 5.736,
    },
  },
  {
    code: "WRTSCTU100",
    name: "Sun Call & Text Unlimited 100",
    description:
      "Unlimited Trinet calls (Sun, Smart & TNT)  Unlimited all-net texts  100MB Data  Valid for 7 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "SUNPH",
    model: "Sun Cellular",
    pricing: {
      unit: "USD",
      price: 2.0,
      dispensingDiscount: 4.4,
      computedAmount: 1.912,
    },
  },
  {
    code: "WRTSCTU150",
    name: "Sun Call & Text Unlimited 150",
    description:
      "Unlimited Trinet calls (Sun, Smart & TNT)  Unlimited all-net texts 500MB Data Valid for 7 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "SUNPH",
    model: "Sun Cellular",
    pricing: {
      unit: "USD",
      price: 3.0,
      dispensingDiscount: 4.4,
      computedAmount: 2.868,
    },
  },
  {
    code: "WRTSCTU450",
    name: "Sun Call & Text Unlimited 450",
    description:
      "Unlimited Trinet Calls (Smart, Sun, and TNT)  Unlimited all-net texts 1.5GB Data Valid for 30 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "SUNPH",
    model: "Sun Cellular",
    pricing: {
      unit: "USD",
      price: 9.0,
      dispensingDiscount: 4.4,
      computedAmount: 8.604,
    },
  },
  {
    code: "WRTSTU150",
    name: "Sun Text Unlimited 150",
    description:
      "Unlimited Sun texts  5 hours Sun Calls  Free Facebook  Nonstop Chat Spinnr access Valid for 30 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "SUNPH",
    model: "Sun Cellular",
    pricing: {
      unit: "USD",
      price: 3.0,
      dispensingDiscount: 4.4,
      computedAmount: 2.868,
    },
  },
  {
    code: "WSOTH300",
    name: "Sun Load 300",
    description: "P300 worth of airtime load valid for 1 year",
    category: "Eload",
    subcategory: "RTR",
    brand: "SUNPH",
    model: "Sun Cellular",
    pricing: {
      unit: "USD",
      price: 6.0,
      dispensingDiscount: 4.4,
      computedAmount: 5.736,
    },
  },
  {
    code: "WSOTH500",
    name: "Sun Load 500",
    description: "P500 worth of airtime load valid for 1 year",
    category: "Eload",
    subcategory: "RTR",
    brand: "SUNPH",
    model: "Sun Cellular",
    pricing: {
      unit: "USD",
      price: 10.0,
      dispensingDiscount: 4.4,
      computedAmount: 9.56,
    },
  },
  {
    code: "WTNTGIGA299",
    name: "TNT Giga Video 299",
    description:
      "4GB + 1GB / day of Video Every Day for YouTube, iFlix, iWant TV, NBA League Pass, Cignal TV, valid for 30 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "TNTPH",
    model: "TNT",
    pricing: {
      unit: "USD",
      price: 6.0,
      dispensingDiscount: 4.4,
      computedAmount: 5.736,
    },
  },
  {
    code: "WTNTGIGA399",
    name: "TNT Giga Video 399",
    description:
      "6GB + 1GB / day of Video Every Day for YouTube, iFlix, iWant TV, NBA League Pass, Cignal TV, valid for 30 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "TNTPH",
    model: "TNT",
    pricing: {
      unit: "USD",
      price: 8.0,
      dispensingDiscount: 4.4,
      computedAmount: 7.648,
    },
  },
  {
    code: "WTNTGIGA499",
    name: "TNT Giga Video 499",
    description:
      "8GB + 1GB / day of Video Every Day for YouTube, iFlix, iWant TV, NBA League Pass, Cignal TV, valid for 30 days",
    category: "Eload",
    subcategory: "RTR",
    brand: "TNTPH",
    model: "TNT",
    pricing: {
      unit: "USD",
      price: 10.0,
      dispensingDiscount: 4.4,
      computedAmount: 9.56,
    },
  },
]

export const getBillerResponse = {
  docs: [
    {
      id: "5e5f1cdb02e76a0017d0ee11",
      name: "2C2P",
      category: "consumer finance",
    },
    {
      id: "5e5f1d7902e76a0017d0ee12",
      name: "99HELP LENDING CORPORATION",
      category: "loans",
    },
    {
      id: "5e60613e02e76a0017d0ee4e",
      name: "ABSMOBILE",
      category: "phone and internet",
    },
    {
      id: "5e5f48f002e76a0017d0ee30",
      name: "AFP General Insurance",
      category: "insurance and financial services",
    },
    {
      id: "5e5f495a02e76a0017d0ee31",
      name: "ALLIEDBANKERS INSURANCE CORPORATION",
      category: "insurance and financial services",
    },
    {
      id: "5e5f1e4702e76a0017d0ee14",
      name: "ASIAPAY PAYMENT TEHNOLOGY CORPORATION",
      category: "payment gateway",
    },
    {
      id: "5e5f712602e76a0017d0ee3e",
      name: "ASTERIA Lending Inc.",
      category: "loans",
    },
    {
      id: "5cf6908e03dd350010b2854f",
      name: "Aboitiz Power",
      category: "electricity",
    },
    {
      id: "5e5f1dc202e76a0017d0ee13",
      name: "Alipay PH",
      category: "payment gateway",
    },
    {
      id: "5e5f1f3502e76a0017d0ee15",
      name: "BTCEXCHANGE.PH",
      category: "payment gateway",
    },
    {
      id: "5cf0e45603dd350010b2853d",
      name: "Bayantel",
      category: "phone and internet",
    },
    {
      id: "5e5f1f8602e76a0017d0ee16",
      name: "Bux.Com Global Limited",
      category: "payment gateway",
    },
    {
      id: "5e5f1fe402e76a0017d0ee17",
      name: "BuyBitcoin.ph",
      category: "payment gateway",
    },
    {
      id: "5e5f226f02e76a0017d0ee19",
      name: "CASH MART ASIA LENDING INC",
      category: "loans",
    },
    {
      id: "5e5f4a3a02e76a0017d0ee33",
      name: "CEBUANA LHUILLIER INSURANCE SOLUTIONS INC",
      category: "insurance and financial services",
    },
    {
      id: "5e5f4b8d02e76a0017d0ee34",
      name: "CIBELES INSURANCE CORPORATION",
      category: "insurance and financial services",
    },
    {
      id: "5e5f716f02e76a0017d0ee3f",
      name: "CREDITBPO TECH INC",
      category: "loans",
    },
    {
      id: "5e5f71c002e76a0017d0ee40",
      name: "Cropital",
      category: "loans",
    },
    {
      id: "5e6061fd02e76a0017d0ee4f",
      name: "Digitel Communications",
      category: "phone and internet",
    },
    {
      id: "5e5f43e902e76a0017d0ee2b",
      name: "E-CENSUS",
      category: "government",
    },
    {
      id: "5e5f22d302e76a0017d0ee1a",
      name: "E-PESO",
      category: "consumer finance",
    },
    {
      id: "5e5f4d0002e76a0017d0ee36",
      name: "ETERNAL PLANS, INC.",
      category: "insurance and financial services",
    },
    {
      id: "5e5f232302e76a0017d0ee1b",
      name: "FUNDKO, INC.",
      category: "loans",
    },
    {
      id: "5e5f778402e76a0017d0ee44",
      name: "FWD Life Insurance Corporation",
      category: "insurance and financial services",
    },
    {
      id: "5e5f4d9c02e76a0017d0ee37",
      name: "FWD Peace",
      category: "insurance and financial services",
    },
    {
      id: "5d68c359841d900011dd3e6f",
      name: "Global Mobility Services",
      category: "loans",
    },
    {
      id: "5e5f238902e76a0017d0ee1c",
      name: "Global Pinoy Remittance and Services Inc.",
      category: "consumer finance",
    },
    {
      id: "5e5f247702e76a0017d0ee1d",
      name: "Green Money Tree Lending Corp.",
      category: "loans",
    },
    {
      id: "5e5f7a9502e76a0017d0ee47",
      name: "ISABELA 1 ELECTRIC COOPERATIVE INC. (ISELCO I)",
      category: "electricity",
    },
    {
      id: "5e5f4dda02e76a0017d0ee38",
      name: "LEX Services",
      category: "insurance and financial services",
    },
    {
      id: "5e5f53d702e76a0017d0ee39",
      name: "LOYOLA PLANS CONSOLIDATED INC.",
      category: "insurance and financial services",
    },
    {
      id: "5e5f3c6a02e76a0017d0ee1e",
      name: "Lendeez",
      category: "loans",
    },
    {
      id: "5e60611002e76a0017d0ee4d",
      name: "MAGNIFICAT VENTURES CORP. (MVC / St. Theres Columbarium)",
      category: "real estate",
    },
    {
      id: "5e5f58d302e76a0017d0ee3b",
      name: "MEDICARD PHILIPPINES INC (CAD)",
      category: "healthcare",
    },
    {
      id: "5e5f74ea02e76a0017d0ee41",
      name: "MOOLALENDING",
      category: "loans",
    },
    {
      id: "5e5f445e02e76a0017d0ee2c",
      name: "Maritime Industry Authority",
      category: "government",
    },
    {
      id: "5e5f585402e76a0017d0ee3a",
      name: "Maxicare",
      category: "healthcare",
    },
    {
      id: "5e5f3db802e76a0017d0ee1f",
      name: "MetisEtrade",
      category: "consumer finance",
    },
    {
      id: "5e5f3e2c02e76a0017d0ee20",
      name: "Microbnk",
      category: "consumer finance",
    },
    {
      id: "5e5f599202e76a0017d0ee3c",
      name: "NEW CANAAN INSURANCE AGENCY, INC",
      category: "insurance and financial services",
    },
    {
      id: "5e605efb02e76a0017d0ee49",
      name: "NORTHERN NEGROS ELETRIC COOPERATIVE (NONEO)",
      category: "electricity",
    },
    {
      id: "5e5f3e6e02e76a0017d0ee21",
      name: "Nexus R Forward Finance, Inc",
      category: "consumer finance",
    },
    {
      id: "5e5f45ef02e76a0017d0ee2e",
      name: "PNP License To Own and Possess Firearm (LTOPF)",
      category: "government",
    },
    {
      id: "5e5f408002e76a0017d0ee25",
      name: "PROXIMITY FUNDING CREDIT COOPERATIVE",
      category: "consumer finance",
    },
    {
      id: "5e5f3f8a02e76a0017d0ee23",
      name: "Payoneer",
      category: "consumer finance",
    },
    {
      id: "5e5f5a6602e76a0017d0ee3d",
      name: "Philcare",
      category: "healthcare",
    },
    {
      id: "5e5f3fde02e76a0017d0ee24",
      name: "Philippine Life Financial Assurance Corporation",
      category: "insurance and financial services",
    },
    {
      id: "5e5f413b02e76a0017d0ee26",
      name: "ROBOCASH FINANCE PHILIPPINES",
      category: "loans",
    },
    {
      id: "5e5f756402e76a0017d0ee42",
      name: "Radiowealth Finance",
      category: "loans",
    },
    {
      id: "5e5f1c6902e76a0017d0ee10",
      name: "Royal Cable",
      category: "cable tv and internet",
    },
    {
      id: "5e6060e502e76a0017d0ee4c",
      name: "TARLAC I ELETRIC COOPERATIVE, INC. (TARELCO I)",
      category: "electricity",
    },
    {
      id: "5e5f41f402e76a0017d0ee28",
      name: "TOUCAN",
      category: "consumer finance",
    },
    {
      id: "5e5f469b02e76a0017d0ee2f",
      name: "Tanay Rural Bank",
      category: "banks",
    },
    {
      id: "5e5f419302e76a0017d0ee27",
      name: "Tapp Commerce",
      category: "consumer finance",
    },
    {
      id: "5e5f429302e76a0017d0ee29",
      name: "VMoney",
      category: "consumer finance",
    },
    {
      id: "5e5f431902e76a0017d0ee2a",
      name: "Wealth Finance Inc.",
      category: "consumer finance",
    },
    {
      id: "5e5f760102e76a0017d0ee43",
      name: "YesCredit Financing Inc",
      category: "loans",
    },
    {
      id: "5d6747b0841d900011dd3e2a",
      name: "AXA Philippines",
      category: "insurance and financial services",
    },
    {
      id: "5cef87bb03dd350010b2851f",
      name: "AirAsia",
      category: "airlines",
    },
    {
      id: "5d68ccd1841d900011dd3e78",
      name: "Angeles Electric Corporation",
      category: "electricity",
    },
    {
      id: "5d67a3aa841d900011dd3e44",
      name: "Asialink",
      category: "loans",
    },
    {
      id: "5cf0ecb103dd350010b2853f",
      name: "BP Waterworks Inc.",
      category: "water",
    },
    {
      id: "5e302b8802e76a0017d0eded",
      name: "Bacolod City Water District",
      category: "water",
    },
    {
      id: "5e302c4a02e76a0017d0edee",
      name: "Baliwag Water District",
      category: "water",
    },
    {
      id: "5d68cebf841d900011dd3e7b",
      name: "Batangas 2 Electric Cooperative Inc. (BATELEC2)",
      category: "electricity",
    },
    {
      id: "5d68d049841d900011dd3e7d",
      name: "Benguet Electric Coop (BENECO)",
      category: "electricity",
    },
    {
      id: "5d68d1db841d900011dd3e7f",
      name: "CAGAYAN DE ORO WATER (COWD)",
      category: "water",
    },
    {
      id: "5d68d56c841d900011dd3e83",
      name: "CLARK WATER CORPORATION",
      category: "water",
    },
    {
      id: "5cf07d1603dd350010b28529",
      name: "Cablelink",
      category: "cable tv and internet",
    },
    {
      id: "5d68d40c841d900011dd3e81",
      name: "Camarines Sur II Electric Cooperative(CASURECO2)",
      category: "electricity",
    },
    {
      id: "5d664a4a841d900011dd3e0b",
      name: "Cashalo",
      category: "insurance and financial services",
    },
    {
      id: "5d68d4b1841d900011dd3e82",
      name: "Cebu II Electric Cooperative (CEBECO2)",
      category: "electricity",
    },
    {
      id: "5cf0e24403dd350010b2853b",
      name: "Cebu Pacific",
      category: "airlines",
    },
    {
      id: "5cf0a1d003dd350010b28531",
      name: "Cignal TV",
      category: "cable tv and internet",
    },
    {
      id: "5d674c02841d900011dd3e2d",
      name: "Cocolife",
      category: "insurance and financial services",
    },
    {
      id: "5cf08dfd03dd350010b2852e",
      name: "Converge ICT",
      category: "cable tv and internet",
    },
    {
      id: "5d68d5c9841d900011dd3e84",
      name: "Cotabato Light",
      category: "electricity",
    },
    {
      id: "5cf0c02303dd350010b28535",
      name: "Davao Light",
      category: "electricity",
    },
    {
      id: "5d67a6e6841d900011dd3e4c",
      name: "Easycash",
      category: "loans",
    },
    {
      id: "5d67afbe841d900011dd3e4e",
      name: "Equicom Savings",
      category: "banks",
    },
    {
      id: "5d67ba1a841d900011dd3e52",
      name: "Finaswide",
      category: "loans",
    },
    {
      id: "5d664be6841d900011dd3e0c",
      name: "Flexi Finance",
      category: "insurance and financial services",
    },
    {
      id: "5d67bafb841d900011dd3e53",
      name: "Fuse Lending",
      category: "insurance and financial services",
    },
    {
      id: "5d8e0500841d900011dd3eba",
      name: "Globe At Home",
      category: "phone and internet",
    },
    {
      id: "5d8e06ae841d900011dd3ebb",
      name: "Globe Postpaid",
      category: "phone and internet",
    },
    {
      id: "5d664f76841d900011dd3e0d",
      name: "Gloriosa Finance Corp",
      category: "insurance and financial services",
    },
    {
      id: "5d6ccb5b841d900011dd3e8d",
      name: "Happy Well Management and Collection Services Inc",
      category: "water",
    },
    {
      id: "5d6ccf40841d900011dd3e8f",
      name: "Ilocos Sur Electric Cooperative, Inc.(ISECO)",
      category: "electricity",
    },
    {
      id: "5d6ceaac841d900011dd3e92",
      name: "LAGUNA WATER DISTRICT AQUATECH RESOURCES CORP.",
      category: "water",
    },
    {
      id: "5cf0c53003dd350010b28536",
      name: "Laguna Water",
      category: "water",
    },
    {
      id: "5d6ceca3841d900011dd3e93",
      name: "Legazpi Water",
      category: "water",
    },
    {
      id: "5d6cedb7841d900011dd3e94",
      name: "Lima Enerzone Corporation",
      category: "electricity",
    },
    {
      id: "5ced0bd0faac810017bef177",
      name: "MERALCO",
      category: "electricity",
    },
    {
      id: "5ced0f00faac810017bef178",
      name: "Maynilad Water Services Inc.",
      category: "water",
    },
    {
      id: "5d6740af841d900011dd3e29",
      name: "Medicard Philippines Inc (USD)",
      category: "healthcare",
    },
    {
      id: "5cf0ebdf03dd350010b2853e",
      name: "Metrobank/PSB Credit Cards",
      category: "banks",
    },
    {
      id: "5d666c36841d900011dd3e1e",
      name: "National Bureau of Investigation (NBI)",
      category: "government",
    },
    {
      id: "5e311d2402e76a0017d0edf2",
      name: "National Housing Authority (NHA)",
      category: "government",
    },
    {
      id: "5d6d04f6841d900011dd3e9e",
      name: "OLONGAPO ELECTRICITY DISTRIBUTION COMPANY INC. (OEDC)",
      category: "electricity",
    },
    {
      id: "5d6d042e841d900011dd3e9d",
      name: "Obando Water District",
      category: "water",
    },
    {
      id: "5cf09eed03dd350010b28530",
      name: "PLDT",
      category: "phone and internet",
    },
    {
      id: "5cf0ccaa03dd350010b28539",
      name: "Pahiram",
      category: "loans",
    },
    {
      id: "5d6d08b3841d900011dd3ea0",
      name: "Pampanga 1 Elec Coop. Inc. (PELCO1)",
      category: "electricity",
    },
    {
      id: "5d6e15f7841d900011dd3ea2",
      name: "Pampanga Rural Electric Service Coop. (PRESCO)",
      category: "electricity",
    },
    {
      id: "5d6778b2841d900011dd3e39",
      name: "Paramount Life",
      category: "insurance and financial services",
    },
    {
      id: "5cece24efaac810017bef174",
      name: "PhilHealth International",
      category: "government",
    },
    {
      id: "5d679a41841d900011dd3e3a",
      name: "Philamlife",
      category: "insurance and financial services",
    },
    {
      id: "5d6e18e5841d900011dd3ea6",
      name: "Pili Water District",
      category: "water",
    },
    {
      id: "5d6e1a19841d900011dd3ea7",
      name: "Plaridel Water District",
      category: "water",
    },
    {
      id: "5d6e1c1e841d900011dd3ea8",
      name: "Primewater",
      category: "water",
    },
    {
      id: "5d679c1e841d900011dd3e3e",
      name: "Prudential Life",
      category: "insurance and financial services",
    },
    {
      id: "5cf679d203dd350010b28549",
      name: "SMART Broadband",
      category: "phone and internet",
    },
    {
      id: "5d6e4433841d900011dd3eac",
      name: "SORSOGON II ELECTRIC COOPERATIVE, INC (SORECO II)",
      category: "electricity",
    },
    {
      id: "5e303b3602e76a0017d0edf0",
      name: "Sta. Lucia Waterworks",
      category: "water",
    },
    {
      id: "5d6f5a64841d900011dd3eae",
      name: "Sta. Maria Water District (SMWD)",
      category: "water",
    },
    {
      id: "5d679d6b841d900011dd3e40",
      name: "Standard Insurance",
      category: "insurance and financial services",
    },
    {
      id: "5d6f5dfb841d900011dd3eaf",
      name: "Subic Enerzone",
      category: "electricity",
    },
    {
      id: "5d679f42841d900011dd3e41",
      name: "Sun Life of Canada Phils",
      category: "insurance and financial services",
    },
    {
      id: "5d6f5f6e841d900011dd3eb1",
      name: "Tabaco Water (TAWAD)",
      category: "water",
    },
    {
      id: "5d6f680c841d900011dd3eb3",
      name: "Tagum Water District",
      category: "water",
    },
    {
      id: "5d6668d0841d900011dd3e1c",
      name: "Union Bank Visa Credit",
      category: "banks",
    },
  ],
  totalDocs: 121,
  limit: 121,
  hasPrevPage: false,
  hasNextPage: false,
  page: 1,
  totalPages: 1,
}

export const getBillerByIdResponse = {
  id: "5e5f495a02e76a0017d0ee31",
  name: "ALLIEDBANKERS INSURANCE CORPORATION",
  category: "insurance and financial services",
  serviceCode: "DP_ALLIEDBANKERS",
  status: "active",
  form: [
    {
      fieldName: "First Name",
      fieldRules: [
        {
          inputTypeOption: "Not applicable.",
          inputFormat: "First Name",
          requiredField: true,
          hidden: false,
          inputType: "text",
          dataType: "nvarchar",
          elementName: "first_name",
          minFieldLength: 1,
          maxFieldLength: 50,
          state: "enabled",
        },
      ],
    },
    {
      fieldName: "Last Name",
      fieldRules: [
        {
          inputTypeOption: "Not applicable.",
          inputFormat: "Last Name",
          requiredField: true,
          hidden: false,
          inputType: "text",
          dataType: "nvarchar",
          elementName: "last_name",
          minFieldLength: 1,
          maxFieldLength: 50,
          state: "enabled",
        },
      ],
    },
    {
      fieldName: "Account Number",
      fieldRules: [
        {
          inputTypeOption: "Not applicable.",
          inputFormat: "Account Number",
          requiredField: true,
          hidden: false,
          inputType: "text",
          dataType: "numeric",
          elementName: "account_number",
          minFieldLength: 1,
          maxFieldLength: 50,
          state: "enabled",
        },
      ],
    },
    {
      fieldName: "Mobile Number",
      fieldRules: [
        {
          inputTypeOption: "Not applicable.",
          inputFormat: "Mobile Number",
          requiredField: true,
          hidden: false,
          inputType: "text",
          dataType: "numeric",
          elementName: "mobile_number",
          minFieldLength: 1,
          maxFieldLength: 50,
          state: "enabled",
        },
      ],
    },
    {
      fieldName: "Amount to Pay",
      fieldRules: [
        {
          inputTypeOption: "Not applicable.",
          inputFormat: "1000.00",
          requiredField: true,
          hidden: false,
          inputType: "text",
          dataType: "money",
          elementName: "billAmount",
          minFieldLength: 1,
          maxFieldLength: 999999,
          state: "enabled",
        },
      ],
    },
  ],
}

export const topUpTransactionResponse = {
  status: "Processing",
  referenceNumber: "T1909301717157d0",
  accountName: "Juan Dela Cruz",
  mobileNumber: "639992280684",
  wallet: "MAIN",
  walletType: "TU",
  currency: "USD",
  amountToBeDeducted: 1.912,
  walletToBeDeducted: "Top-up Wallet",
  walletDeduction: 1.912,
  transactionDate: "2019-09-30T09:17:15.912Z",
  productName: "Smart Load 100",
  productPrice: 2.0,
  rebate: {
    rebateProductPrice: 0.0,
    rebatePercentage: 0.0,
    rebateAmount: 0.0,
    dealerRebatePercentage: 0.0,
    dealerRebateCommission: 0.0,
  },
  dispensingDiscount: 4.4,
  dealerDispensingDiscount: 0.0,
  dealerCommission: 0.0,
}
